name: Wolfi Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  wolfi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🔥 Setup melange
      - name: Setup melange
        uses: chainguard-dev/actions/setup-melange@eab208ef2d05b13404296a5e194a6b237e8bb213
        with:
          version: latest-release

      # 🔥 Setup apko
      - name: Setup apko
        uses: chainguard-dev/actions/setup-apko@eab208ef2d05b13404296a5e194a6b237e8bb213

      # 🔥 Build package
      - name: Build package
        uses: chainguard-dev/actions/melange-build@eab208ef2d05b13404296a5e194a6b237e8bb213
        with:
          config: melange.yaml
          archs: x86_64
          sign-with-temporary-key: true

      # 🔥 Build image
      - name: Build image
        uses: chainguard-dev/actions/apko-build@eab208ef2d05b13404296a5e194a6b237e8bb213
        with:
          config: apko.yaml
          tag: your.registry/controller:${{ github.ref_name }}
