name: Wolfi Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  wolfi:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout
      # ----------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Melange
      # ----------------------------
      - name: Setup Melange
        uses: chainguard-dev/setup-melange@v1

      # ----------------------------
      # Setup Apko
      # ----------------------------
      - name: Setup Apko
        uses: chainguard-dev/setup-apko@v1

      # ----------------------------
      # Build Wolfi Package
      # ----------------------------
      - name: Build package
        run: melange build melange.yaml

      # ----------------------------
      # Login to your registry
      # ----------------------------
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # ----------------------------
      # Build and Push Image
      # ----------------------------
      - name: Build and push image
        run: |
          IMAGE="${{ secrets.REGISTRY_URL }}/${{ github.repository }}:${{ github.ref_name }}"

          apko build apko.yaml "$IMAGE" image.tar

          docker load < image.tar
          docker push "$IMAGE"
