name: Ko Image
on:
    push:
        branches:
            - main
        tags:
            - "v*"

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
                  cache: false
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Configure git for private modules
              run: |
                  git config --global url."git@github.com:ntlaletsi70/".insteadOf "https://github.com/ntlaletsi70/"

            - name: Setup ko
              uses: ko-build/setup-ko@v0.7

            - name: Login to registry
              run: |
                  echo "${{ secrets.REGISTRY_PASSWORD }}" | ko login ${{ secrets.REGISTRY_URL }} \
                    --username ${{ secrets.REGISTRY_USERNAME }} \
                    --password-stdin

            - name: Build and push
              env:
                  KO_DOCKER_REPO: docker.io/nkanyezisolutions/blanketops-environments-controller
                  GOPRIVATE: github.com/ntlaletsi70/*
                  GONOSUMDB: github.com/ntlaletsi70/*
                  GOPROXY: direct
                  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
              run: |
                  ko build ./cmd/main.go \
                    --bare \
                    --platform linux/amd64,linux/arm64 \
                    --tags ${{ github.ref_name }},latest
